// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ksnujqbnaszcwgxtbweg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzbnVqcWJuYXN6Y3dneHRid2VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1MjgyMjcsImV4cCI6MjA5MjEwNDIyN30.5ld9stQks3AI5IAyrlgKc473qAhwO4wDoLobqZUrjHg";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);